version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    # Keep the codeql-action sub-actions in one PR
    groups:
      codeql:
        patterns:
          - 'github/codeql-action*'
